### ISSUE TITLE
Unable to contact local SharpPad server

### ISSUE THREAD

**Issue by CodeByNate** [jmazouri/SharpPad#12]
I am unable to run SharpPad.   Yes. I have tried adding a firewall exception and disabling firewall completely.  Here is the trace:

Unable to contact local SharpPad server. Please ensure "Output.Port" is correct (currently 5255).

Unhandled Exception: System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)       
   at SharpPad.Output.MakeHttpRequest(Func`2 request)
   at SharpPad.Output.SendContent(String serialized)
   at SharpPad.Output.DumpInternal(Object input, String title, Boolean withStackTrace)
   at SharpPad.Output.Dump[T](T input, String title)
   at DumpingTest.Program.Main(String[] args) in C:\Users\username\source\learncs\MCPD\Chapter04\DumpingTest\Program.cs:line 11
   at DumpingTest.Program.<Main>(String[] args)

**Comment by QingCold** [comment]
Same problem
